POST http://localhost:3000/cursos/programacion

###
PUT http://localhost:3000/cursos/programacion HTTP/1.1

###
POST http://localhost:3000/cursos/programacion HTTP/1.1
Content-Type: application/application/json

{
    "titulo": "aprende Node.js"
}
